services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    entrypoint: '/app/bin/start-server.sh'
    environment:
      - DJANGO_SECRET='django-insecure-4r$a!&5%2t*qd4g$zn=$hh&5^%q4(81#%0aw!7@at^r15h$%d_'
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:17-bullseye
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
