services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    entrypoint: '/app/bin/start-server.sh'
    environment:
      - DJANGO_SECRET='django-insecure-4r$a!&5%2t*qd4g$zn=$hh&5^%q4(81#%0aw!7@at^r15h$%d_'
    env_file:
      - .env
    depends_on:
      - database
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  pdadmin4:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
  celery:
    build: 
      context: .
    user: 'server-user'
    command: celery -A core worker -l INFO
    volumes:
      - ./src:/app
    depends_on:
      - app
      - redis
    env_file:
      - .env
      
  database:
    image: postgres:17-bullseye
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  dev-db-data:
  pgadmin-data:
